language: java
jdk: oraclejdk8

script:
  - ant compile jar

deploy:
  # GitHub - Add zip to release
  - provider: releases
    api_key: ${key}
    file: /home/travis/build/namila007/Fractal/build/jar/Fractal.jar
    skip_cleanup: true
    on:
     all_branches: true
